/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Client3 } from "./Client3";

export class Client3Factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Client3 {
    return new Contract(address, _abi, signerOrProvider) as Client3;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "id",
        type: "uint256",
      },
      {
        name: "response1",
        type: "string",
      },
      {
        name: "response2",
        type: "string",
      },
      {
        name: "response3",
        type: "string",
      },
    ],
    name: "callback",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
