/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SampleContestInterface extends ethers.utils.Interface {
  functions: {
    "bond(bytes32,uint256)": FunctionFragment;
    "bytes32ToString(bytes32)": FunctionFragment;
    "bytesToAddr(bytes)": FunctionFragment;
    "coord()": FunctionFragment;
    "curves(bytes32)": FunctionFragment;
    "curves_list(uint256)": FunctionFragment;
    "getEndpoints()": FunctionFragment;
    "getOwner()": FunctionFragment;
    "getStatus()": FunctionFragment;
    "getTokenAddress(bytes32)": FunctionFragment;
    "initializeContest(address,uint256)": FunctionFragment;
    "initializeCurve(bytes32,bytes32,int256[])": FunctionFragment;
    "isEndpointValid(bytes32)": FunctionFragment;
    "judge(bytes32)": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "redeemed(address)": FunctionFragment;
    "redeemed_list(uint256)": FunctionFragment;
    "reserveToken()": FunctionFragment;
    "reset()": FunctionFragment;
    "settle()": FunctionFragment;
    "status()": FunctionFragment;
    "toBytes(address)": FunctionFragment;
    "tokenFactory()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "ttl()": FunctionFragment;
    "unbond(bytes32,uint256)": FunctionFragment;
    "winValue()": FunctionFragment;
    "winner()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bond",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32ToString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bytesToAddr",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "coord", values?: undefined): string;
  encodeFunctionData(functionFragment: "curves", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "curves_list",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEndpoints",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "getStatus", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTokenAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeContest",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeCurve",
    values: [BytesLike, BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isEndpointValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "judge", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "redeemed", values: [string]): string;
  encodeFunctionData(
    functionFragment: "redeemed_list",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reset", values?: undefined): string;
  encodeFunctionData(functionFragment: "settle", values?: undefined): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(functionFragment: "toBytes", values: [string]): string;
  encodeFunctionData(
    functionFragment: "tokenFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "ttl", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unbond",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "winValue", values?: undefined): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytesToAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "coord", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "curves", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "curves_list",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEndpoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeContest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeCurve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isEndpointValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "judge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeemed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemed_list",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toBytes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ttl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unbond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winValue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;

  events: {
    "Bonded(bytes32,uint256,address)": EventFragment;
    "Closed()": EventFragment;
    "DotTokenCreated(address)": EventFragment;
    "Initialized(address)": EventFragment;
    "Judged(bytes32)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Reset()": EventFragment;
    "Settled(uint256,uint256)": EventFragment;
    "Unbonded(bytes32,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Bonded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Closed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DotTokenCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Judged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Reset"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Settled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unbonded"): EventFragment;
}

export class SampleContest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SampleContestInterface;

  functions: {
    bond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "bond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bytes32ToString(x: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "bytes32ToString(bytes32)"(
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    bytesToAddr(b: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "bytesToAddr(bytes)"(
      b: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    coord(overrides?: CallOverrides): Promise<[string]>;

    "coord()"(overrides?: CallOverrides): Promise<[string]>;

    curves(arg0: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "curves(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    curves_list(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "curves_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getEndpoints(overrides?: CallOverrides): Promise<[string[]]>;

    "getEndpoints()"(overrides?: CallOverrides): Promise<[string[]]>;

    getOwner(overrides?: CallOverrides): Promise<[string]>;

    "getOwner()"(overrides?: CallOverrides): Promise<[string]>;

    getStatus(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getStatus()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTokenAddress(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getTokenAddress(bytes32)"(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initializeContest(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initializeContest(address,uint256)"(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeCurve(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initializeCurve(bytes32,bytes32,int256[])"(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isEndpointValid(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isEndpointValid(bytes32)"(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    judge(
      endpoint: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "judge(bytes32)"(
      endpoint: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    "oracle()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    redeemed(arg0: string, overrides?: CallOverrides): Promise<[number]>;

    "redeemed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    redeemed_list(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "redeemed_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    reserveToken(overrides?: CallOverrides): Promise<[string]>;

    "reserveToken()"(overrides?: CallOverrides): Promise<[string]>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "reset()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    settle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "settle()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    status(overrides?: CallOverrides): Promise<[number]>;

    "status()"(overrides?: CallOverrides): Promise<[number]>;

    toBytes(
      x: string,
      overrides?: CallOverrides
    ): Promise<[string] & { b: string }>;

    "toBytes(address)"(
      x: string,
      overrides?: CallOverrides
    ): Promise<[string] & { b: string }>;

    tokenFactory(overrides?: CallOverrides): Promise<[string]>;

    "tokenFactory()"(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ttl(overrides?: CallOverrides): Promise<[BigNumber]>;

    "ttl()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    unbond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "unbond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    winValue(overrides?: CallOverrides): Promise<[BigNumber]>;

    "winValue()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    winner(overrides?: CallOverrides): Promise<[string]>;

    "winner()"(overrides?: CallOverrides): Promise<[string]>;
  };

  bond(
    endpoint: BytesLike,
    numDots: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "bond(bytes32,uint256)"(
    endpoint: BytesLike,
    numDots: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bytes32ToString(x: BytesLike, overrides?: CallOverrides): Promise<string>;

  "bytes32ToString(bytes32)"(
    x: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  bytesToAddr(b: BytesLike, overrides?: CallOverrides): Promise<string>;

  "bytesToAddr(bytes)"(
    b: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  coord(overrides?: CallOverrides): Promise<string>;

  "coord()"(overrides?: CallOverrides): Promise<string>;

  curves(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

  "curves(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  curves_list(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "curves_list(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getEndpoints(overrides?: CallOverrides): Promise<string[]>;

  "getEndpoints()"(overrides?: CallOverrides): Promise<string[]>;

  getOwner(overrides?: CallOverrides): Promise<string>;

  "getOwner()"(overrides?: CallOverrides): Promise<string>;

  getStatus(overrides?: CallOverrides): Promise<BigNumber>;

  "getStatus()"(overrides?: CallOverrides): Promise<BigNumber>;

  getTokenAddress(
    endpoint: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "getTokenAddress(bytes32)"(
    endpoint: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  initializeContest(
    oracleAddress: string,
    _ttl: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initializeContest(address,uint256)"(
    oracleAddress: string,
    _ttl: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeCurve(
    endpoint: BytesLike,
    symbol: BytesLike,
    curve: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initializeCurve(bytes32,bytes32,int256[])"(
    endpoint: BytesLike,
    symbol: BytesLike,
    curve: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isEndpointValid(
    _endpoint: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isEndpointValid(bytes32)"(
    _endpoint: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  judge(
    endpoint: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "judge(bytes32)"(
    endpoint: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  oracle(overrides?: CallOverrides): Promise<string>;

  "oracle()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  redeemed(arg0: string, overrides?: CallOverrides): Promise<number>;

  "redeemed(address)"(arg0: string, overrides?: CallOverrides): Promise<number>;

  redeemed_list(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "redeemed_list(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  reserveToken(overrides?: CallOverrides): Promise<string>;

  "reserveToken()"(overrides?: CallOverrides): Promise<string>;

  reset(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "reset()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  settle(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "settle()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  status(overrides?: CallOverrides): Promise<number>;

  "status()"(overrides?: CallOverrides): Promise<number>;

  toBytes(x: string, overrides?: CallOverrides): Promise<string>;

  "toBytes(address)"(x: string, overrides?: CallOverrides): Promise<string>;

  tokenFactory(overrides?: CallOverrides): Promise<string>;

  "tokenFactory()"(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ttl(overrides?: CallOverrides): Promise<BigNumber>;

  "ttl()"(overrides?: CallOverrides): Promise<BigNumber>;

  unbond(
    endpoint: BytesLike,
    numDots: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "unbond(bytes32,uint256)"(
    endpoint: BytesLike,
    numDots: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  winValue(overrides?: CallOverrides): Promise<BigNumber>;

  "winValue()"(overrides?: CallOverrides): Promise<BigNumber>;

  winner(overrides?: CallOverrides): Promise<string>;

  "winner()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    bond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "bond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    bytes32ToString(x: BytesLike, overrides?: CallOverrides): Promise<string>;

    "bytes32ToString(bytes32)"(
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    bytesToAddr(b: BytesLike, overrides?: CallOverrides): Promise<string>;

    "bytesToAddr(bytes)"(
      b: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    coord(overrides?: CallOverrides): Promise<string>;

    "coord()"(overrides?: CallOverrides): Promise<string>;

    curves(arg0: BytesLike, overrides?: CallOverrides): Promise<string>;

    "curves(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    curves_list(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "curves_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getEndpoints(overrides?: CallOverrides): Promise<string[]>;

    "getEndpoints()"(overrides?: CallOverrides): Promise<string[]>;

    getOwner(overrides?: CallOverrides): Promise<string>;

    "getOwner()"(overrides?: CallOverrides): Promise<string>;

    getStatus(overrides?: CallOverrides): Promise<BigNumber>;

    "getStatus()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenAddress(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "getTokenAddress(bytes32)"(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    initializeContest(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "initializeContest(address,uint256)"(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    initializeCurve(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    "initializeCurve(bytes32,bytes32,int256[])"(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;

    isEndpointValid(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isEndpointValid(bytes32)"(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    judge(endpoint: BytesLike, overrides?: CallOverrides): Promise<void>;

    "judge(bytes32)"(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    oracle(overrides?: CallOverrides): Promise<string>;

    "oracle()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    redeemed(arg0: string, overrides?: CallOverrides): Promise<number>;

    "redeemed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<number>;

    redeemed_list(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "redeemed_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    reserveToken(overrides?: CallOverrides): Promise<string>;

    "reserveToken()"(overrides?: CallOverrides): Promise<string>;

    reset(overrides?: CallOverrides): Promise<void>;

    "reset()"(overrides?: CallOverrides): Promise<void>;

    settle(overrides?: CallOverrides): Promise<void>;

    "settle()"(overrides?: CallOverrides): Promise<void>;

    status(overrides?: CallOverrides): Promise<number>;

    "status()"(overrides?: CallOverrides): Promise<number>;

    toBytes(x: string, overrides?: CallOverrides): Promise<string>;

    "toBytes(address)"(x: string, overrides?: CallOverrides): Promise<string>;

    tokenFactory(overrides?: CallOverrides): Promise<string>;

    "tokenFactory()"(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ttl(overrides?: CallOverrides): Promise<BigNumber>;

    "ttl()"(overrides?: CallOverrides): Promise<BigNumber>;

    unbond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "unbond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winValue(overrides?: CallOverrides): Promise<BigNumber>;

    "winValue()"(overrides?: CallOverrides): Promise<BigNumber>;

    winner(overrides?: CallOverrides): Promise<string>;

    "winner()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    Bonded(
      endpoint: BytesLike | null,
      numDots: BigNumberish | null,
      sender: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { endpoint: string; numDots: BigNumber; sender: string }
    >;

    Closed(): TypedEventFilter<[], {}>;

    DotTokenCreated(
      tokenAddress: null
    ): TypedEventFilter<[string], { tokenAddress: string }>;

    Initialized(
      oracle: string | null
    ): TypedEventFilter<[string], { oracle: string }>;

    Judged(winner: null): TypedEventFilter<[string], { winner: string }>;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    Reset(): TypedEventFilter<[], {}>;

    Settled(
      winValue: null,
      winTokens: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { winValue: BigNumber; winTokens: BigNumber }
    >;

    Unbonded(
      endpoint: BytesLike | null,
      amount: BigNumberish | null,
      sender: string | null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { endpoint: string; amount: BigNumber; sender: string }
    >;
  };

  estimateGas: {
    bond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "bond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bytes32ToString(
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "bytes32ToString(bytes32)"(
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytesToAddr(b: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "bytesToAddr(bytes)"(
      b: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    coord(overrides?: CallOverrides): Promise<BigNumber>;

    "coord()"(overrides?: CallOverrides): Promise<BigNumber>;

    curves(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "curves(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    curves_list(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "curves_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEndpoints(overrides?: CallOverrides): Promise<BigNumber>;

    "getEndpoints()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOwner(overrides?: CallOverrides): Promise<BigNumber>;

    "getOwner()"(overrides?: CallOverrides): Promise<BigNumber>;

    getStatus(overrides?: CallOverrides): Promise<BigNumber>;

    "getStatus()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenAddress(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTokenAddress(bytes32)"(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializeContest(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initializeContest(address,uint256)"(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeCurve(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initializeCurve(bytes32,bytes32,int256[])"(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isEndpointValid(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isEndpointValid(bytes32)"(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    judge(
      endpoint: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "judge(bytes32)"(
      endpoint: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    "oracle()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    redeemed(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "redeemed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    redeemed_list(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "redeemed_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reserveToken(overrides?: CallOverrides): Promise<BigNumber>;

    "reserveToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "reset()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    settle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "settle()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    status(overrides?: CallOverrides): Promise<BigNumber>;

    "status()"(overrides?: CallOverrides): Promise<BigNumber>;

    toBytes(x: string, overrides?: CallOverrides): Promise<BigNumber>;

    "toBytes(address)"(
      x: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokenFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ttl(overrides?: CallOverrides): Promise<BigNumber>;

    "ttl()"(overrides?: CallOverrides): Promise<BigNumber>;

    unbond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "unbond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    winValue(overrides?: CallOverrides): Promise<BigNumber>;

    "winValue()"(overrides?: CallOverrides): Promise<BigNumber>;

    winner(overrides?: CallOverrides): Promise<BigNumber>;

    "winner()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "bond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bytes32ToString(
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bytes32ToString(bytes32)"(
      x: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytesToAddr(
      b: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bytesToAddr(bytes)"(
      b: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    coord(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "coord()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    curves(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "curves(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    curves_list(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "curves_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEndpoints(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getEndpoints()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getOwner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getStatus()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTokenAddress(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTokenAddress(bytes32)"(
      endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializeContest(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initializeContest(address,uint256)"(
      oracleAddress: string,
      _ttl: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeCurve(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initializeCurve(bytes32,bytes32,int256[])"(
      endpoint: BytesLike,
      symbol: BytesLike,
      curve: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isEndpointValid(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isEndpointValid(bytes32)"(
      _endpoint: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    judge(
      endpoint: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "judge(bytes32)"(
      endpoint: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "oracle()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeemed(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "redeemed(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeemed_list(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "redeemed_list(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reserveToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "reserveToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "reset()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    settle(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "settle()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    status(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "status()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    toBytes(
      x: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "toBytes(address)"(
      x: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenFactory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ttl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ttl()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unbond(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "unbond(bytes32,uint256)"(
      endpoint: BytesLike,
      numDots: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    winValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "winValue()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    winner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "winner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
