/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TestClientInterface extends ethers.utils.Interface {
  functions: {
    "callback(uint256,bytes32[])": FunctionFragment;
    "cancelQuery(uint256)": FunctionFragment;
    "testQuery(address,string,bytes32,bytes32[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "callback",
    values: [BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelQuery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "testQuery",
    values: [string, string, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "callback", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testQuery", data: BytesLike): Result;

  events: {
    "MadeQuery(address,string,uint256)": EventFragment;
    "Result1(uint256,string)": EventFragment;
    "Result2(uint256,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MadeQuery"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Result1"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Result2"): EventFragment;
}

export class TestClient extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TestClientInterface;

  functions: {
    "callback(uint256,bytes32[])"(
      id: BigNumberish,
      response: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "callback(uint256,string)"(
      id: BigNumberish,
      response1: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "callback(uint256,string,string)"(
      id: BigNumberish,
      response1: string,
      response2: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelQuery(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelQuery(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    testQuery(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "testQuery(address,string,bytes32,bytes32[])"(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  "callback(uint256,bytes32[])"(
    id: BigNumberish,
    response: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "callback(uint256,string)"(
    id: BigNumberish,
    response1: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "callback(uint256,string,string)"(
    id: BigNumberish,
    response1: string,
    response2: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelQuery(
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "cancelQuery(uint256)"(
    id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  testQuery(
    oracleAddr: string,
    query: string,
    specifier: BytesLike,
    params: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "testQuery(address,string,bytes32,bytes32[])"(
    oracleAddr: string,
    query: string,
    specifier: BytesLike,
    params: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    "callback(uint256,bytes32[])"(
      id: BigNumberish,
      response: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "callback(uint256,string)"(
      id: BigNumberish,
      response1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "callback(uint256,string,string)"(
      id: BigNumberish,
      response1: string,
      response2: string,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelQuery(id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "cancelQuery(uint256)"(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    testQuery(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "testQuery(address,string,bytes32,bytes32[])"(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    MadeQuery(oracle: null, query: null, id: null): EventFilter;

    Result1(id: null, response1: null): EventFilter;

    Result2(id: null, response1: null, response2: null): EventFilter;
  };

  estimateGas: {
    "callback(uint256,bytes32[])"(
      id: BigNumberish,
      response: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "callback(uint256,string)"(
      id: BigNumberish,
      response1: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "callback(uint256,string,string)"(
      id: BigNumberish,
      response1: string,
      response2: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelQuery(id: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "cancelQuery(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    testQuery(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "testQuery(address,string,bytes32,bytes32[])"(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "callback(uint256,bytes32[])"(
      id: BigNumberish,
      response: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "callback(uint256,string)"(
      id: BigNumberish,
      response1: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "callback(uint256,string,string)"(
      id: BigNumberish,
      response1: string,
      response2: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelQuery(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelQuery(uint256)"(
      id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    testQuery(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "testQuery(address,string,bytes32,bytes32[])"(
      oracleAddr: string,
      query: string,
      specifier: BytesLike,
      params: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
