/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Upgradable } from "./Upgradable";

export class UpgradableFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Upgradable {
    return new Contract(address, _abi, signerOrProvider) as Upgradable;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "updateDependencies",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        name: "c",
        type: "address",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
];
